# Name your project
name: 'dbt_training'
version: '1.0.0'
config-version: 2

# Profile used by dbt
profile: 'default'

# Project paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"


# Model configurations
models:
  dbt_training:

    # All models under models/example/
    example:
      +materialized: table

    # All models under models/staging/
    staging:
      +materialized: table



# Seed configurations
seeds:
  dbt_training:
    +schema: reference
    +quote_columns: false