version: 2

sources:
  - name: emp
    database: >-
      {%- if target.database == 'DEV' -%} DEV_RAW
      {%- elif target.database == 'QA' -%} QA_RAW
      {%- elif target.database == 'PROD' -%} PROD_RAW
      {%- else -%} INVALID_DATABASE
      {%- endif -%}
    schema: hris
    tables:
      - name: emp
        identifier: emp_s